### ISSUE TITLE
DevTools failed to load SourceMap: Could not load content for chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/shared-data.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by mgomez-tubs** [vuejs/vue-devtools#1322]
### Version
6.0.0-beta.2

### Browser and OS info
w10 / latest chrome / vuejs3 ver 3.0.4

### Steps to reproduce
Run a local vuejs site (as a development build), then open vuejs devtools tab in chrome.

### What is expected?
Normal Behaviour

### What is actually happening?
FIle under ./build/shared-data.js.map doesnt exist

**Comment by mgomez-tubs** [comment]
Solved by reverting to Vue 3.0.2

**Comment by mgomez-tubs** [comment]
Solved by reverting to Vue 3.0.2

**Comment by softboy99** [comment]
Hi
I encounter same problem.  After reverting to Vue 3.0.2, still the same, does there need any configureation in vue.config.js or any other places?

**Comment by mgomez-tubs** [comment]
Reverting doesnt solve the issue. I thought it was gone, but it wasn't showing show since I didn't have the DevTools tap open. The needed script "shared-data.js.map" seems to be missing  under %AppData%\Local\Google\Chrome\User Data\Default\Extensions\ljjemllljcmogpfapbkkighbhhppjdbg\6.0.0.2_0\build

**Comment by weleoka** [comment]
Not sure if this is related, in Firefox (78.4.0esr (64-bit)) it is similar with the Vue devtools extension 6.0.0.2, and under Vue v3.0.2 or v3.0.4:

```
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://f99ab60a-8fd9-4773-891b-b12fdf395fe2/build/backend.js
Source Map URL: shared-data.js.map
```

**Comment by bassneck** [comment]
Same issue on devtools 6.0.0 beta3 on chrome 87.0.4280.88

```
DevTools failed to load SourceMap: Could not load content for chrome-extension://ljjemllljcmogpfapbkkighbhhppjdbg/build/queue.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by KrzysztofPoz** [comment]
same issue on  devtools 6.0.0 beta3 on Chromium Version 83.0.4103.116 built on Debian

**Comment by Akryum** [comment]
The sourcemap file failing to load doesn't have any impact on the running code, so you can safely ignore this error.
