### ISSUE TITLE
Uncaught ReferenceError: o is not defined

### ISSUE THREAD

**Issue by yoyo837** [vuejs/vue-devtools#514]
When simulating mobile devices...Long press a button, tools report error about a second later.

**Edit: Or right click and it immediately report the error**

```javascript
    document.addEventListener("contextmenu", t=>{
        const n = t.target;
        if (n) {
            const t = Object(o.a)(n); // here
            if (t)
                return e.__VUE_DEVTOOLS_CONTEXT_MENU_HAS_TARGET__ = !0,
                void (e.__VUE_DEVTOOLS_CONTEXT_MENU_TARGET__ = t)
        }
        e.__VUE_DEVTOOLS_CONTEXT_MENU_HAS_TARGET__ = null,
        e.__VUE_DEVTOOLS_CONTEXT_MENU_TARGET__ = null
    }
    )
```

### Version
4.0.0

### Browser and OS info
Chrome 63/ Win 10 FCU

### Steps to reproduce
1.Long press a button
2.report error

### What is expected?
No mistake

### What is actually happening?
report error

**Comment by Akryum** [comment]
I can't reproduce this. Also, the code you posted doesn't exist. Here is the compiled code in the extension:

```js
document.addEventListener("contextmenu", t=>{
    let n = t.target;
    if (n) {
        for (; !n.__vue__ && n.parentElement; )
            n = n.parentElement;
        const t = n.__vue__;
        if (t)
            return e.__VUE_DEVTOOLS_CONTEXT_MENU_HAS_TARGET__ = !0,
            void (e.__VUE_DEVTOOLS_CONTEXT_MENU_TARGET__ = t)
    }
    e.__VUE_DEVTOOLS_CONTEXT_MENU_HAS_TARGET__ = null,
    e.__VUE_DEVTOOLS_CONTEXT_MENU_TARGET__ = null
}
)
```

Try to remove and reinstall the extension.

**Comment by yoyo837** [comment]
![d74b732e-e1bb-42a2-a3d7-a150ffafc709](https://user-images.githubusercontent.com/6134547/34938020-c1ef65c0-fa21-11e7-8aba-21932beb46cf.jpeg)
![2c42b7f8-bb8e-42c1-beb3-760b7d856e16](https://user-images.githubusercontent.com/6134547/34938021-c23553c8-fa21-11e7-818e-ccd5236abc72.jpeg)
![0234ba0d-8106-497d-8124-065aeaec9522](https://user-images.githubusercontent.com/6134547/34938023-c2771b46-fa21-11e7-908d-81dd33c6b50e.jpeg)

I did just try and still happens.

**Comment by yoyo837** [comment]
build with this commit: a79d9c55176ed8146b3631256a869d6938209c3e

**Comment by yoyo837** [comment]
#525  Possible related issues

**Comment by UncleBill** [comment]
Got a same issue.

**Comment by patriciussanctus** [comment]
+1

**Comment by f3l1x** [comment]
Got the same issue. 

```
Uncaught ReferenceError: o is not defined
    at HTMLDocument.document.addEventListener.t (<anonymous>:1:783)
```

**Comment by ratiw** [comment]
@Akryum After your fix in #528, I've also seen this, the first time Vue-Devtools is run. 

This can now be seen in the same sample [here](https://2wk5wvxrj.codesandbox.io/) (the same url sample in #528). This seems to happen only the first time Vue-Devtools is initialized.

Steps to reproduce
- Install Vue-Devtools from this branch [https://github.com/Akryum/vue-devtools/tree/types-improvements](https://github.com/Akryum/vue-devtools/tree/types-improvements)
- Closed all developer tools windows (where vue-devtools is in)
- Click this [url](https://2wk5wvxrj.codesandbox.io/) to open the sample project in CodeSandbox

Sometimes this error pops right away on the page. Sometimes you need to click on the page a few times and it will display the error instead of the rendered content. In one of my project, it displays in the developer tools' console window.

When reloading the page the second time (without closing Vue-devtools), the error is gone.

**Comment by Akryum** [comment]
@ratiw I can't reproduce on the branch.

**Comment by ratiw** [comment]
@Akryum After revisit it again, it actually happens when I **"right-click"** the window.

Please see the attached gif.

![vue-devtools-error](https://user-images.githubusercontent.com/807017/35196797-a9822508-ff09-11e7-9fb2-99e7b9843b6e.gif)

**Comment by f3l1x** [comment]
Confirmed, mouse right-click trigged it in my Chrome also.

**Comment by TheDutchCoder** [comment]
I have this issue on pages where Vue isn't loaded at all, so not sure why the plugin is listening.

![image](https://user-images.githubusercontent.com/1668207/35353096-1bf6423e-0114-11e8-9785-18908a43293d.png)

**Comment by mazinsw** [comment]
Same issue here, when right clicked on any page, version tested: 4.1.0

**Comment by tribakzero** [comment]
Seems to be related to the contextual menu that displays the "inspect vue component" with latest Vue.js, I'm installing it and it's fresh, also having the issue.

**Comment by anteriovieira** [comment]
Fixed in https://github.com/vuejs/vue-devtools/pull/553

**Comment by f3l1x** [comment]
@anteriovieira Well, I'm using NWjs (node-webkit) with Vue + Vue DevTools and the error still remains.

**Comment by anteriovieira** [comment]
@f3l1x, the fix should come in the next version.

**Comment by yGuy** [comment]
You should release that version ASAP. Or even consider disabling the current version of the plugin altogether until you have released that version: 
The plugin is breaking other web applications: whenever you right click on them the onerror handler on the window is triggered. Those web apps that report this error (silently or to the user) all look broken, now. 
We get lots of reports from the users of our apps regarding this issue. This makes web pages look bad, when in fact it's the vue.js devtools plugin that is badly programmed. 
IMHO the plugin should be written with try/catches all over. In case of programming errors the _plugin_ should never trigger the _web pages_'s error handler.

**Comment by Akryum** [comment]
Are your users using the Vue devtools?

**Comment by yGuy** [comment]
As soon as you have a certain user base, there are some among them, who are using it. Do you always disable the plugin when you don't develop with vue? I don't. (or rather: I didn't).
So obviously: yes, some of them have the plugin installed. It doesn't matter whether you are using it. Having it installed seems to be enough.

**Comment by Akryum** [comment]
Until 4.1.1 is out they can disable it then.

**Comment by anteriovieira** [comment]
@yGuy the error is only thrown when the vue tab is triggered. If the user does not open the devtools and select the vue tab then the error is not related to vue-devtools.

**Comment by yGuy** [comment]
The point is: How do I tell them, that it's not my page that is broken, but its the damn plugin that is totally unrelated? I cannot send an email to all my users and tell them about the plugin. I don't even have their contact data.  When will 4.1.1. be out?

**Comment by Akryum** [comment]
@anteriovieira This can happen even if the devtools are not open.

**Comment by Akryum** [comment]
> I cannot send an email to all my users and tell them about the plugin. I don't even have their contact data.

Why don't you have any mean of supporting your users?

**Comment by Akryum** [comment]
>  When will 4.1.1. be out?

Very soon.

**Comment by yyx990803** [comment]
4.1.1 has been pushed to chrome web store, it should be live any time.

**Comment by candu** [comment]
4.1.1 is out, not experiencing this bug anymore on my end (user agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36`).  Thanks for fixing this!

**Comment by hackel** [comment]
Thanks for the fix @Akryum!  This issue also affected the extension on Firefox and it is now fixed as well.

Please ignore the complainers.  Users need to understand that any time they install an extension and grant permission to inject javascript on any page, they are opening 3rd party sites up to breakage.  That's not on you at all.  Developers should know better.

**Comment by f3l1x** [comment]
Confirm, it's fixed for my and NW.js environment.
