### ISSUE TITLE
Vuex state not loading

### ISSUE THREAD

**Issue by alexbowers** [vuejs/vue-devtools#773]
### Version
5.0.0-beta.3

### Browser and OS info
Chrome 68.0.3440.106, Mac OS X 10.13.5

### Steps to reproduce
Open an application, have some mutations happen. Inspect one and you'll see "Loading State" and it never changes.

Clicking Export of state will give `"__vue_devtool_undefined__"` to the clipboard.

It is also not working when in "Recording state" and you click "Load state"

### What is expected?
To view the full state at the time of the inspection.

### What is actually happening?
Mutation is visible, but the state as a whole is not.

![image](https://user-images.githubusercontent.com/842974/45616632-fe8f4480-ba67-11e8-8bf8-8706e9edcaaa.png)

**Comment by Akryum** [comment]
Do you have a minimal reproduction please? It's working fine in our e2e tests.

**Comment by zefman** [comment]
Seeing the same issue on a project too. Can't pinpoint what is causing it, but we use a lot of dynamic Vuex modules so might be something to do with that?

@alexbowers do you have any dynamic modules in your project?

**Comment by tochoromero** [comment]
I'm seeing the same behavior as well, I do have dynamic modules.

**Comment by murbanowicz** [comment]
I have the same issue.

**Comment by siberiadev** [comment]
Ooops! 
![image](https://user-images.githubusercontent.com/42664395/46051416-fae87580-c16b-11e8-827f-c6eaa04f50ed.png)

**Comment by gonzaloserrano** [comment]
Same here.

**Comment by ronildo** [comment]
I also have the same issue, stays like this forever.

![screen shot 2018-10-01 at 8 04 57 am](https://user-images.githubusercontent.com/622159/46287499-b8021580-c550-11e8-9538-79501a6afde6.png)

**Comment by kematzy** [comment]
> Ooops!
> ![image](https://user-images.githubusercontent.com/42664395/46051416-fae87580-c16b-11e8-827f-c6eaa04f50ed.png)

I'm having both these problems in both Chrome (69.0.3497.100) and Firefox (v62.02) on OS X (v10.12.6). 

I believe I have pinpointed the area where things go wrong (at least in my code/on my system).

## STEPS TO REPRODUCE

### 1) Console log after page reload

Note the `console.log()` output. I'm loading data from Firebase and storing the retrieved data in the Vuex state, and things are stored correctly.

![01-console-output-vue-devtools-beta](https://user-images.githubusercontent.com/6571/46331971-e06f3a00-c64c-11e8-8c47-38cc5d5494ca.png)

### 2)  The same app state shown in Vue DevTools (beta v5.0.0 beta3)

Note the "Recording State" message that never goes away.

![02-devtools-output-vue-devtools-beta](https://user-images.githubusercontent.com/6571/46332096-70ad7f00-c64d-11e8-839e-54b2491832d6.png)

### 3)  Vue DevTools display after clicking "Load state" button
Note, that all previous mutations of the state, is now missing.

![03-devtools-loaded-output-vue-devtools-beta](https://user-images.githubusercontent.com/6571/46332192-efa2b780-c64d-11e8-8b5b-a536a20d03dc.png)

### 4) Vue DevTools display after clicking "Commit This Mutation" button

Note that state output is altered (see 'currentUser') compared to previous screen (above)

![04-devtools-committed-output-vue-devtools-beta](https://user-images.githubusercontent.com/6571/46332243-38f30700-c64e-11e8-8ba7-36661bf65c4b.png)


### 5) Finding the Culprit through the Console

After reviewing the Console output, I found that **the last mutation had been called two more times** with the **entire state as the payload**, instead of the real actual payload.

![05-console-after-committed-output-vue-devtools-beta](https://user-images.githubusercontent.com/6571/46332296-7a83b200-c64e-11e8-8fc3-007a53e62c40.png)

#### Summary

I haven't had the time to investigate the DevTools code, and I don't think I would get where things go wrong within either, but I hope the above will help identify the key areas to review.

The older version of Vue DevTools works fine with the same app.


@siberiadev The issue with your duplicate entries, which I too had, can be solved by a bit of 'defensive' coding, and not storing the whole payload object.

**Example**
```js
    userExtraStore: (state, payload) => {
       // DON'T STORE payload object
      // state.authUser = payload
      
      // INSTEAD, rewrite the object to ensure the parts you want only included.
      state.authUser = {
        email: payload.email,
        name: payload.name,
        role: payload.role,
        verified: payload.verified
      }
    }
``

**Comment by zefman** [comment]
I have had a look into this today, and it seems as though the error occurs because registering a dynamic module doesn't cause the dev-tools to take a new snapshot of the current state. 

Registering a module essentially modifies the state outside of a mutation, so the replayMutations function in src/backend/vuex.js basically is out of sync, and working from state without the module.

Unfortunately I can't see an easy way of hooking in to the registerModule function to trigger a new state snapshot.

**Comment by dgpgdev** [comment]
same error with dynamic register module.

**Comment by H3xx3n** [comment]
We have a similar issue on our project. With the older version of Devtool is working fine but with the latest beta (currently beta 3 also) the store fails to load with this error:
![image](https://user-images.githubusercontent.com/16035455/46617617-76a7d200-cb1d-11e8-8443-b0ffa89922d4.png)
![image](https://user-images.githubusercontent.com/16035455/46617656-8de6bf80-cb1d-11e8-9e1c-7e7d14589d6a.png)

**Comment by dehru** [comment]
I'm also seeing this. I'm a newbie to Vue, but my app works fine until I load the vue devtools in chrome and then it seems the states are "wedged".  Uninstall the vue-devtools and everything works fine again.

**Comment by husayt** [comment]
I have the same problem with Nuxt.

**Comment by Binaryify** [comment]
same

**Comment by davidpelayo** [comment]
✋ happening with dynamic modules as well!

**Comment by gterras** [comment]
Is there any news on this ? This makes developing  complex apps in Vuex (with modules) almost impossible as of right now, stable dev-tools can't handle medium-sized stores and beta dev-tool don't even display stores.

**Comment by Lenderson** [comment]
Same problem here :/

**Comment by ilicmarko** [comment]
I can also confirm this, the state is stuck.

**Version:** 5.0.0 beta 3

![Image](https://i.imgur.com/5TZER7N.png)

**Comment by EnSabanNur** [comment]
Same issue here without dynamic modules.

**Comment by harrywynnwill** [comment]
I have this issue with modules, if I export the state I get `"__vue_devtool_undefined__"`.

**Comment by harrywynnwill** [comment]
I am using an old VueJs devtools chrome extension from here https://crx.dam.io/ext/nhdogjmejiglipccpnnnanhbledajbpd.html

You can drag the zip in here (I had developer mode on)
chrome://extensions/

**Comment by yood** [comment]
I ran into this issue when debugging from VSCode with Chrome. For me at least, it was related to using a custom Chrome user data directory.

**Workaround**

I started seeing Vuex state in devtools again when I used the default user data directory with Chrome. To do that, stop passing --user-data-dir when launching chrome from the command line, or set "userDataDir" to false in launch.json.

Devtools: 5.0.0 beta 3
Chrome 70.0.3538.110 (Official Build) (64-bit)
MacOS 10.14.1
VSCode 1.29.1

**Comment by ffxsam** [comment]
@Akryum Still an issue in 5.0.0 beta 4

**Comment by tradelab** [comment]
I noticed it is still an issue for me when registering state modules using variables for store paths, will try to set a minimal example.

**Comment by gterras** [comment]
I noticed it is still an issue for me when registering state modules using variables for store paths, will try to set a minimal example.

**Comment by szalapski** [comment]
This seems to still be an issue in 5.0.0 beta 4 .  Any ideas?
![image](https://user-images.githubusercontent.com/2723505/54540099-5e0dd480-4965-11e9-9913-744fca4cb213.png)

**Comment by Sp1ker** [comment]
@szalapski 
Can you create public repository with problem for reproduction please?

**Comment by kasuganodayy** [comment]
I'm still getting this problem in 5.0.1.

I can't seem to be able to reproduce getting stuck at Load State, but I was able to reproduce Store states showing as empty after setting values via dispatched actions.
 [Here's a public repo.](https://github.com/kasuganodayy/YouCannotDipGuacamayo)

**Comment by DevBrent** [comment]
Fixed and released in 5.0.3 restart chrome!
https://github.com/vuejs/vue-devtools/releases/tag/v5.0.3

**Comment by sebastianlp** [comment]
Hi. I still have a problem similar to this using the new version pointed by @DevBrent (5.0.3). You can check using the vuex/examples repos, the shopping cart. 

Steps to reproduce:
1. After installing the dependencies and running the example, go to http://localhost:8080/shopping-cart/
2. Open console, go to Vue->Vuex, see the mutations and press "Commit all"
![image](https://user-images.githubusercontent.com/4922264/55080317-be46f980-507c-11e9-9bb3-855938cbbe77.png)
3. Add any product to the cart using the "Add to cart" button, you will see some more mutations, commit them:
![image](https://user-images.githubusercontent.com/4922264/55080408-e46c9980-507c-11e9-8e40-1bd795e03933.png)
4. You will get the console error and the vuex tab will be stucked:
Error:
![image](https://user-images.githubusercontent.com/4922264/55080460-f51d0f80-507c-11e9-88b0-50e99c3a7ddd.png)
Vuex:
![image](https://user-images.githubusercontent.com/4922264/55080507-0a923980-507d-11e9-8f2f-6447d7f16ab3.png)

This also happend in my own repo, with a different data structure of course, but getting same error, trying to commit some mutations that update an array.

Any clues?

**Comment by SnooHD** [comment]
@sebastianlp im having the same issue.
For me it seems the case of using getters with a payload..
```
export const target = (state, getters, rootState, rootGetters) => ({from, target}) => {
}
```

`{from, target}` gets changed by babel to `_ref`.
Then it tries to set `var from = _ref.target` and `var target = _ref.target`..
But because the payload is empty, i get the error and Vue devtools gets stuck loading the state.

**Comment by sean-hill** [comment]
I just downloaded version 5.0.6 of vue devtools, restarted chrome, and I'm still experiencing this issue, stuck on "Loading state" 😦 

![image](https://user-images.githubusercontent.com/1205866/55248428-6db3d580-520f-11e9-80ca-04569b540e5c.png)

**Comment by aotearoacoder** [comment]
Any know of a tracking issue that is open?

**Comment by sebastianlp** [comment]
This issue was opened but fixed: https://github.com/vuejs/vue-devtools/issues/934

**Comment by xaksis** [comment]
This is still an issue. Can we re-open this?

**Comment by Akryum** [comment]
@xaksis Please open a new issue with more details on your problem.

**Comment by ronildo** [comment]
I used to have the same problem, but I don't have it anymore.
Also it's worth mentioning that I had Vue Performance Devtool installed, which also was causing some sort of error, after I disabled it, I didn't get the problem anymore.

**Comment by ebreisman** [comment]
Hopefully this may help someone. I've been using the vuex-persistedstate plugin. I just disabled it and vuex within vue-devtools in Chrome has started working again for me. I tried it with both autoload vuex state enabled and disabled in the vue-devtools settings.

**Comment by mnooblet** [comment]
I've the same issue, the state keeps on loading and hangs, when I click on commit actions the state is empty in devtools and my app crashes with errors because the state get's altered and fucked up.

Re-open

**Comment by Akryum** [comment]
See my previous comment. Vuex state not loading is not detailed enough.

**Comment by gkkirilov** [comment]
Restarting the browser worked for me

**Comment by mtimoustafa** [comment]
I'm also experiencing the same bug on 5.0.9 😞 I just opened a new issue for this, hoping to get some visibility.

**Comment by Zetaphor** [comment]
Anyone else experiencing this on 5.1.0, try disabling the new Vuex backend in settings, this seems to have resolved it for me. Odd seeing that I've been using it fine up until this point.

**Comment by szalapski** [comment]
5.1.0 seems to have resolved this for me for now, whether or not the "new backend" is enabled. I'll come back here if the problem comes up again.

**Comment by daniel-stelle** [comment]
5.1.0 works for me on Chrome, but I still have this issue on Firefox with 5.1.0.

**Comment by Yakoot** [comment]
Vue.js devtools 5.1.0
Vivaldi 2.5.1525.43 (Stable channel) (64-bit) (chrome 74)

dynamic modules

Vuex state not loading and I also dont see the "Loading state" text

**Comment by blackfyre** [comment]
Devtools 5.1.0
Firefox 67.0
Works fine without the new backend...

**Comment by ekosynth** [comment]
Devtools: 5.1.1
Chrome: Version 76.0.3809.132 (Official Build) (32-bit)

I got the same problem as OP, with "Clicking Export of state will give "__vue_devtool_undefined__" to the clipboard."

I tried a different Vue project and the state loaded fine. I thought it might be a problem with my code, so I tried commenting out all Vuex modules one by one and it started working. After re-enabling them all, it kept working. So I think this must be a caching issue somewhere.

**Comment by briedis** [comment]
I experienced a very similar issue.
What I found out that I was mutating the object that was being passed to a mutator:

```    mutations: {
        [Store.SET_INITIAL_STATE](state, data) {
            if (data.myObject) {
                state.myObject = MyClass.fromArray(data.myObject);
            }
        }
    }
```

And in the `fromArray` I was doing:
```
fromArray(obj){
    delete.obj.items; // This mutates the passed object
    return Object.assign(new MyObject, obj);
}
```
I solved it by avoiding mutations of the parameter object. (I cloned the object before mutating).

Apparently, vuex keeps the reference of object, and if you try to replay it, it will use the same object.

Don't mutate mutation parameters - you will have a bad time.
